    <tr bgcolor="<<:color:>>" class="table_row_right" >
	<td sorttable_customkey="<<:run esc:>>" nowrap align=left class="table_row_right"><a class="link" href="shuttle_graph.jsp?run=<<:run:>>&instance=<<:instance enc:>>"><<:run:>></a></td>
	<td sorttable_customkey="<<:runtype esc:>>" nowrap align=left class="table_row_right"><<:runtype:>></td>
	<td sorttable_customkey="<<:first_seen_timestamp esc:>>" nowrap align=right class="table_row_right"><<:first_seen:>></td>
	<td sorttable_customkey="<<:last_seen_timestamp esc:>>" nowrap align=right class="table_row_right"><<:last_seen:>></td>
	<td sorttable_customkey="<<:SHUTTLE_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:SHUTTLE_color:>>" onMouseOver="overlib('SHUTTLE: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:SHUTTLE:>></td>
	<td sorttable_customkey="<<:ACO_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:ACO_color:>>" onMouseOver="overlib('ACO: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:ACO:>></td>
	<td sorttable_customkey="<<:EMC_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:EMC_color:>>" onMouseOver="overlib('EMC: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:EMC:>></td>
	<td sorttable_customkey="<<:FMD_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:FMD_color:>>" onMouseOver="overlib('FMD: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:FMD:>></td>
	<td sorttable_customkey="<<:GRP_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:GRP_color:>>" onMouseOver="overlib('GRP: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:GRP:>></td>
	<td sorttable_customkey="<<:HLT_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:HLT_color:>>" onMouseOver="overlib('HLT: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:HLT:>></td>
	<td sorttable_customkey="<<:HMP_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:HMP_color:>>" onMouseOver="overlib('HMP: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:HMP:>></td>
	<td sorttable_customkey="<<:MCH_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:MCH_color:>>" onMouseOver="overlib('MCH: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:MCH:>></td>
	<td sorttable_customkey="<<:MTR_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:MTR_color:>>" onMouseOver="overlib('MTR: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:MTR:>></td>
	<td sorttable_customkey="<<:PHS_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:PHS_color:>>" onMouseOver="overlib('PHS: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:PHS:>></td>
	<td sorttable_customkey="<<:CPV_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:CPV_color:>>" onMouseOver="overlib('CPV: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:CPV:>></td>
	<td sorttable_customkey="<<:PMD_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:PMD_color:>>" onMouseOver="overlib('PMD: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:PMD:>></td>
	<td sorttable_customkey="<<:SPD_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:SPD_color:>>" onMouseOver="overlib('SPD: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:SPD:>></td>
        <td sorttable_customkey="<<:SDD_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:SDD_color:>>" onMouseOver="overlib('SDD: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:SDD:>></td>
	<td sorttable_customkey="<<:SSD_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:SSD_color:>>" onMouseOver="overlib('SSD: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:SSD:>></td>
	<td sorttable_customkey="<<:TOF_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:TOF_color:>>" onMouseOver="overlib('TOF: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:TOF:>></td>
	<td sorttable_customkey="<<:TPC_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:TPC_color:>>" onMouseOver="overlib('TPC: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:TPC:>></td>
	<td sorttable_customkey="<<:TRD_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:TRD_color:>>" onMouseOver="overlib('TRD: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:TRD:>></td>
	<td sorttable_customkey="<<:TRI_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:TRI_color:>>" onMouseOver="overlib('TRI: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:TRI:>></td>
	<td sorttable_customkey="<<:T00_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:T00_color:>>" onMouseOver="overlib('T00: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:T00:>></td>
	<td sorttable_customkey="<<:V00_state esc:>>" nowrap align=left  class="table_row_right" bgcolor="<<:V00_color:>>" onMouseOver="overlib('V00: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:V00:>></td>
	<td sorttable_customkey="<<:ZDC_state esc:>>" nowrap align=left  class="table_row" bgcolor="<<:ZDC_color:>>" onMouseOver="overlib('ZDC: Run number: <<:run:>> <br> <<:runtype js:>>');" onMouseOut="return nd();"><<:ZDC:>></td>
    </tr>
